= kTor
Adrien Pessu
Gautier de Saint Martin Lacaze
ifndef::imagesdir[:imagesdir: ../images]
ifndef::sourcedir[:sourcedir: ../../main/kotlin]


== Un peu de théorie

=== kTor

kTor est un Framework développé par JetBrain pour créer rapidement des applications web (servlet 3.0) ou API REST. kTor propose des bibliothèques pour réaliser une application complète. kTor est construit autour des coroutines de Kotlin et est donc asynchrone par nature. Toutes les fonctionnalités de kTor sont testables facilement.

==== Voici comment créer une application REST avec kTor
```
import io.ktor.server.netty.*
import io.ktor.routing.*
import io.ktor.application.*
import io.ktor.http.*
import io.ktor.response.*
import io.ktor.server.engine.*

fun main(args: Array<String>) {
    embeddedServer(Netty, 8080) {
        routing {
            get("/") {
                call.respondText("Hello, world!", ContentType.Text.Html)
            }
        }
    }.start(wait = true)
}
```

Pour utiliser kTor sur un projet Kotlin, il suffit d'ajouter la dependance : 
```
compile "io.ktor:ktor-server-core:0.9.3"
```
pour gradle

Le site http://ktor.io[ktor.io] permet de créer des templates d'application selon votre besoin (comme le fait http://start.spring.io)


== Exercice 3

[source]
----
git checkout step3
----

Nous avons ajouté kTor (Voir `build.gradle` et `Main.kt`)

Ajouter un point d'entré REST pour afficher notre liste.


