= Les `companion`, vos meilleurs amis
Adrien Pessu
Gautier de Saint Martin Lacaze
ifndef::imagesdir[:imagesdir: ../images]
ifndef::sourcedir[:sourcedir: ../../main/kotlin]


== Un peu de théorie

=== Static method

Contrairement à Java, Kotlin ne supporte pas les méthodes statiques pour une classe.
En fait, les méthodes statiques n'appartiennent pas à l'instance de l'objet mais plutôt au type lui-même.
De ce fait, il est conseillé en Kotlin de définir les méthodes, que l'on veut statique, directement au niveau du package.

[source, kotlin]
----
fun toUpperCase(input:String):String{
    return if(input.isEmpty()) "" else input.toUpperCase()
}
----

La méthode précédente pourra être appelé directement (sans instance d'un objet) de la façon suivante :

[source, kotlin]
----
fun main(args: Array<String>) {
    val message = "Kotlin : le back du futur"
    println("Initial case: $message")
    println("Upper case: " + toUpperCase(message))
}
----

Puisque l'on vient de voir les méthodes statiques, on peut se demander comment déclarer un singleton.
Pour rappel, le singleton est un pattern de programmation limitant l'instanciation d'une classe à une unique instance.
Une fois l'instance créée, elle "vivra" tout au long de la durée de vie de votre programme.

Voici un singleton en Kotlin :

[source, kotlin]
----
object MonSingleton {
    private var count = 0
    fun callMe():Unit {
        println("Ça fait $count fois que je suis appelé !")
    }
}
----

Avec l'exemple précédent, on peut appeler directement notre méthode via `MonSingleton.callMe()`.

=== `companion`

Maintenant que l'on a présenté la façon de déclarer une méthode statique et un singleton, on peut se demander comment peut on faire pour avoir une méthode statique dans une classe comme en Java.
C'est à ce moment là que le `companion` (ou `companion object`) est utile.

Ce sera notamment utile dans le cas où l'on veut créer une factory.

[source, kotlin]
----
class User private constructor(val login: String) {
    companion object UserFactory {
        fun create(login: String): User {
            return User(login)
        }
    }
}
----

NOTE: Comme vous pouvez le remarquer le constructeur de `User` est privé.
Il n'est donc pas possible d'instancier `User` en dehors de sa classe.

NOTE: Le `companion` a également accès à toutes les méthodes ainsi que tous les membres de la classe `User`.

NOTE: Il est possible de "nommer" un `companion` en utilisant la syntaxe suivante : `companion object MonCompanion {}`.
Il sera alors possible d'appeler le companion dans la classe principale via `MonCompanion`.

Pour appeler la méthode de création d'un `User`, vous devez utiliser le code suivant :

[source, kotlin]
----
User.UserFactory.create("myLogin")
----

Comme c'est un peu long et que Kotlin pense aux développeurs, vous pouvez utiliser le raccourci suivant :

[source, kotlin]
----
User.create("myLogin")
----

Vous trouverez plus d'informations sur les `companion` sur https://kotlinlang.org/docs/reference/object-declarations.html#companion-objects[cette page]

== Exercice 3

Après autant de théorie, repassons à la pratique.
Nous allons créer notre premier `companion` dans la classe `EventController`.

Afin de commancer l'exercice suivant, faites un checkout du step1.

[source]
----
git checkout step1
----


Ce compagnon aura la charge à la fois de remplacer le filtre utilisé dans la méthode `get`, mais également de rendre les données plus "jolie".

* Ajouter le `companion` `Letter` à la classe `EventController`
* Ajouter une méthode nommée `prettier` au `companion`
** la méthode prendra en paramètre une liste d'`Event` et retournera le type `Any`
** la méthode permettra de filter les événements sans date
* Remplacer le filtre actuellement dans la méthode `get`par votre nouveau `companion`

Pour vous aider, il y a des tests unitaires sur step1.

== Un peu de théorie

=== Paramètre nommé

Contrairement à Java, Kotlin fourni le support des paramètres nommés.
Ceux-ci nous permettent notamment d'être explicites sur le nommage des arguments lorsqu'ils sont passés à une fonction.
Cela à l'avantage d'expliciter les appels notament lorsqu'il y a de nombreux arguments.


Dans l'exemple suivant, il n'est pas aisé de savoir à quoi correspond chaque valeur passé en paramètre.

[source, kotlin]
----
val string = "Kotlin is a great language"
string.endsWith("Great Language", true)
----

Avec les paramètres nommés cela devient beaucoup plus lisible.

[source, kotlin]
----
val string = "Kotlin is a great language"
string.endsWith(suffix = "Great Language", ignoreCase = true)
----

Un autre bénéfice des paramètres nommés est la possibilité pour le code appelant la fonction de réorganiser l'ordre des paramètres.
Le code suivant est toujours valide.

[source, kotlin]
----
val string = "Kotlin is a great language"
string.endsWith(ignoreCase = true, suffix = "Great Language")
----

WARNING: Les paramètres nommés ne peuvent être utilisés que sur des fonctions définies par Kotlin et non sur des fonctions définies par Java.
Cela est dû au fait que le code Java, lorsqu'il est compilé en bytecode, ne conserve pas toujours les noms des paramètres.


Vous trouverez plus d'informations sur les `paramètre nommé` sur https://kotlinlang.org/docs/reference/functions.html#named-arguments[cette page]


=== Paramètre par défaut


Il est souvent utile de définir des paramètres par défaut pour nos méthodes.
En Java, cela se traduit par l'overloading.
On a alors un code au format suivant

[source, java]
----
public void myFunction(String string, boolean ignoreCase) {
    // do stuff
}

public void myFunction(String string) {
    myFunction(string, false);
}
----

Kotlin fournit une alternative très intéressante.
Il est possible dans la définition d'une fonction de préciser des valeurs par défaut.
L'équivalent du code Java précédent serait le suivant en Kotlin.

[source, kotlin]
----
fun myFunction(string: String, ignoreCase: Boolean = false): Unit {
    // do stuff
}
----

On peut alors appeler notre code de la façon suivante.

[source, kotlin]
----
myFunction("call without default parameter", true)
myFunction("call with default parameter")
----


Vous trouverez plus d'informations sur les `paramètres par défaut` sur https://kotlinlang.org/docs/reference/functions.html#default-arguments[cette page]


=== Copy

Comme promis au début de ce codelab, nous allons aborder rapidement la méthode copy des `Data class`.
Pour rappel, lorsque l'on déclare une `Data class`, on obtient une méthode de copie prête à l'emploi.
Cette méthode vous permet de créer une nouvelle instance de votre type tout en sélectionnant les champs que vous souhaitez modifier.
Par exemple, vous pouvez décider que vous souhaitez obtenir une nouvelle instance d'une classe `Event` à partir d'une instance existante dont vous souhaitez simplement modifier les champs de date et de lieu.

[source, kotlin]
----
event.copy(location = "Tours", date = "2018-02-23")
----

=== String templates

En tant que développeurs Java, nous sommes familiers avec l'utilisation de la concaténation de chaînes de caractères.
Si l'on garde la pattern appris en Java cela donnerait le code suivant en Kotlin.

[source, kotlin]
----
val name = "TouraineTech"
print("Hello " + name)
----

Les `String templates` sont un moyen simple et efficace d'incorporer des valeurs, des variables ou même des expressions dans une chaîne sans avoir besoin d'utiliser la concaténation précédente.

Les `String templates` améliorent l'expérience du développeur lors de l'utilisation de plusieurs variables dans un seul littéral.
En effet, ils conservent la chaîne plus courte et plus lisible.
L'utilisation est extrêmement simple. Une valeur ou une variable peut être intégrée simplement par préfixer avec un symbole dollar ($):

[source, kotlin]
----
val name = "TouraineTech"
print("hello $name")
----

Là où ça devient intéressant pour le templating, c'est qu'il existe plusieurs format de `String`.
Pour le moment nous avons vu le `String correspondant` à celui en Java avec la forme suivante `val name = "TouraineTech"`.
Il existe également le `raw String`.
Il se déclare de la façon suivante.

[source, kotlin]
----
val text = """
    |Tell me and I forget.
    |Teach me and I remember.
    |Involve me and I learn.
    |(Benjamin Franklin)
    """.trimMargin()
----

NOTE: Par défaut le "|" est utilisé comme préfixe indiquant la position de la marge gauche du `raw string`.
On peut néanmois choisir un autre caractère et le passer en paramètre de la méthode `trimMargin`.
Par exemple, `trimMargin(">")`.


Vous trouverez plus d'informations sur les `String template` sur https://kotlinlang.org/docs/reference/basic-types.html#string-literals[cette page]


== Exercice 4

Dans l'exercice 3, nous avons créé notre `companion` avec une méthode nommé `prettier`.
Nous allons maintenant enrichir cette méthode pour transformer les dates du format chiffre vers le format lettres.

* Ajouter un tableau de valeurs contenant les chaines de caractères pour les chiffres 0 à 9 en anglais
** Pour 1, on utilisera "one"
** ...
* Dans votre méthode `prettier`, pour chaque date, remplacer chaque chiffre par son équivalent en chaîne de charactères

Pour vous aider, il y a des tests unitaires sur step1.

== Corrigé

Nous vous invitons à regarder https://github.com/bttf-kotlin/kotlin-codelab-bttf/blob/7d1cea87a33fc6f13e2244c62c4f9df9731585e3/src/main/kotlin/com/github/kotlincodelabbttf/controllers/EventController.kt#L24-L28[notre solution] pour la comparer avec la votre.
Notamment la contruction de la chaîne de caractères.
