= Gestion de la nullité et initialisation tardive
Adrien Pessu
Gautier de Saint Martin Lacaze
ifndef::imagesdir[:imagesdir: ../images]
ifndef::sourcedir[:sourcedir: ../../main/kotlin]

== Un peu de théorie

=== La mort de l'opérateur ternaire

Bon ok, c'est peut être un peu pour le buzz.

Pour le moment, on n'a pas encore parlé des conditions. Les fameux `if`.
Tout comme en Java il est possible d'utiliser le if en tant que gestionnaire du flux d'éxécution (désolé, nous n'avons pas trouvé mieux comme traduction française de flow control).

[source, kotlin]
----
val a = 10
val b = 11

if (a < b) {
    print ("Youhou a est inférieur à b")
}

// Version avec un else
if (a < b) {
    print ("Youhou a est inférieur à b")
} else {
    print ("Youhou b est inférieur à a")
}
----

Il existe une autre façon d'utiliser le `if` et c'est pourquoi on peut parle plus ou mois de la fin de l'opérateur ternaire (le fameux `= ? :`).
En Kotlin, `if` est une expression.
Il est donc possible de s'en servir pour remplacer l'opérateur ternaire.

[source, kotlin]
----
val max = if (a > b) a else b
----

On peut même imaginer plus complexe avec l'exemple suivant.

[source, kotlin]
----
val max = if (a > b) {
    print("Youhou a est le plus grand")
    a
} else {
    print("Youhou b est le plus grand")
    b
}
----

Vous trouverez plus d'informations sur les `String template` sur https://kotlinlang.org/docs/reference/control-flow.html#if-expression[cette page]


=== Gestion du null

Le système de type de Kotlin vise à éliminer le danger des références nulles à partir du code.
Ce problème est également connu sous le nom de https://en.wikipedia.org/wiki/Tony_Hoare#Apologies_and_retractions[The Billion Dollar Mistake].
Bien entendu on parle de la fameuse NullPointerException de Java (aka NPE).

Pour régler ce problème, Kotlin ne permet pas par défaut d'avoir des références nulles.
Le code suivant est donc *invalide*.

[source, kotlin]
----
var kotlin: String = "Kotlin for the win !"
kotlin = null // Le code ne compile pas
----

Il est possible de déclarer une variable nulle.
Dans ce cas nous utiliserons une précision syntaxique pour indiquer que l'on autorise le null.

[source, kotlin]
----
var java: String? = "Java for the NPE"
java = null // Dans ce cas le code compile
----

NOTE: Notez bien l'utilisation du `?` dans la déclaration de la variable `java`.

A part la déclaration explicite d'une variable nulle, il existe d'autres cas pouvant générer une NPE :

* un appel à `throw NullPointerException()`
* l'utilisation de l'opérateur !! (non présenté dans cette partie cf. le site officiel de Kotlin)
* un problème de données inconsistantes lors de l'initialisation
* l'intéraction avec du code Java


Alors qu'est ce qui change entre nos deux morceaux de code précédent.

Pour le premier, c'est simple l'appel suivant sera valide.

[source, kotlin]
----
val length = kotlin.length
----

Pour le second, ce n'est pas le cas.


[source, kotlin]
----
val length = java.length // Erreur de compilation
----

Le compilateur va nous forcer à gérer les cas de la nullité.
Et clairement c'est un gros progrès par rapport au compilateur Java.
Pour la gestion de la nullité, on peut alors utiliser le `if else` traditionnel, ou bien le `safe call operator` `?.`.

[source, kotlin]
----
val length: Int? = java?.length // Ici ça compile
----

La valeur de `length` sera soit la taille de `java` si `java` est valorisé, ou alors `null`.

NOTE: On peut remarquer que le type de length sera alors `Int?` et non pas `Int`

Là où cela devient très intéressant c'est que l'on peut chaîner les opérateurs `?.`.


[source, kotlin]
----
val profileLabel = user?.profile?.label
----

Dans le cas précédent, `profileLabel` sera `null` si `user` est `null` ou si `profile` est `null`.

Vous trouverez plus d'informations sur les `String template` sur https://kotlinlang.org/docs/reference/null-safety.html#nullable-types-and-non-null-types[cette page]


== Exercice 5

Afin de commancer l'exercice suivant, faites un checkout du step2.

[source]
----
git checkout step2
----

Reprenons notre projet et enrichissons un peu notre code.
Nous allons maintenant permettre à notre endpoint d'API de gérer deux cas d'affichage.
Le premier sera l'affichage sans transformation de la date des événements, le second sera celui que l'on a mis en place dans l'exercice précédent.

* Ajouter un paramètre optionnel dans la méthode get de `EventController`
* En fonction du paramètre d'entrée, utiliser ou non le `companion`
** on vous laisse choisir les valeurs permettant ou non d'utiliser le `companion`

Pour vous aider, il y a des tests unitaires sur step2.

== Un peu de théorie

Depuis la version 1.2 de Kotlin il est possible d'initialiser plus tard une `val` dans le code.
Pour cela il faut utiliser le modifier `lateinit`.
Cela est notamment utile lors de l'utilisation d'une lambda dans un constructeur.

[source, kotlin]
----
// A cycle of three nodes:
lateinit var third: Node<Int>

val second = Node(2, next = { third })
val first = Node(1, next = { second })

third = Node(3, next = { first })
----

Pour éviter les problèmes lors de l'utilisation des variables déclarée avec le modifier `lateinit`, il est possible d'utiliser la méthode  `isInitialized`

[source, kotlin]
----
println("isInitialized before assignment: " + this::lateinitVar.isInitialized)
lateinitVar = "value"
println("isInitialized after assignment: " + this::lateinitVar.isInitialized)
----

NOTE: Le modifier `lateinit` est régulièrement utilisé dans les projets Spring.
L'injection de dépendance pourra toujours être effectuée sans problème et le code compilera.

Vous trouverez plus d'informations sur le `lateinit` sur http://kotlinlang.org/docs/reference/whatsnew12.html#lateinit-top-level-properties-and-local-variables[cette page].


== Exercice 6

Ici nous n'allons pas coder, mais simplement découvrir l'utilisation du `lateinit` dans le cadre d'un projet Spring.

Regarder le code de la classe https://github.com/bttf-kotlin/kotlin-codelab-bttf/blob/3b2d6914c80f00180ff57b01608576049bc33632/src/main/kotlin/com/github/kotlincodelabbttf/controllers/EventController.kt#L13-L14[`EventController`].


